name: bs2
channels:
- conda-forge
dependencies:
- colorama
- coloredlogs
- geopandas
- netcdf4
- numpy[version='<1.25']
- pandas
- pip
- python
- rioxarray
- setuptools_scm
- xarray
pip:
  - spatialnc
  - inicheck

